# Generated by Django 5.0.1 on 2024-02-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_permission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='documentReason',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='permission',
            name='imageReason',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='permission',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='reason',
            field=models.TextField(),
        ),
    ]
