# Generated by Django 5.0.1 on 2024-02-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_permission_documentreason_permission_imagereason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='isApproved',
        ),
    ]
