# Generated by Django 5.0.2 on 2024-02-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_permission_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_Approved',
            field=models.BooleanField(default=False),
        ),
    ]
